server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&AllowPublicKeyRetrieval=True
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 2425540101@qq.com
    password: vdsnweeizoxwdhhe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.chenzhihui.community.entity

community:
  path:
    domain: http://localhost:8080
    upload: /Users/chenzhihui/Desktop/JavaProject/NiuKeForumData/NiuKeForum/upload



